name: Deploy Hardhat Contract to Monad Testnet

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Compile contracts
        run: npx hardhat compile

      - name: Deploy contract
        run: npx hardhat run deploy/deploy.js --network monadTestnet
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
